config/routes.rb
MxitToDo::Application.routes.draw do

  match '/add' => 'list#add', :as => :add_item, :via => [:get, :post]

  match '/complete/:id' => 'list#complete', :as => :complete_item

  root :to => 'list#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :content, :date, :priority
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # The body style is automatically applied to all pages
  mxit_style :body, 'background-color:#FFFFFF; color:#333333'

  # The title style is automatically applied to the page title
  mxit_style :title, 'padding:4px 6px; background-color:#998888; color:#ffffff;'

  # Links can only be styled on a per-page basis, not per link.  The :hover link is used 
  mxit_style :link_hover, 'background-color: #EA1A76; color: #ffffff;'
  mxit_style :link, 'color: #EA1A76;'

end

app/controllers/list_controller.rb
class ListController < ApplicationController

  include MxitRails::Page

  def index
    @items = Item.all
  end

  def add
    @content = params[:content]

    form do
      step :content do
        input :content, 'What do you need to do?'
      end

      step :priority do
        input :priority, 'How important is it?'
        validate :numeric, 'Please enter a number between 1 and 5'
        validate 'Please enter a number between 1 and 5' do |input|
          (1..5).include? input.to_i
        end
        # TODO: Nice single-select input
      end

      step :date do
        input :date, 'When does it need to be done by?'
        #TODO: Nice date input
      end
    end

    submit do
      item = Item.new
      item.content = params[:content]
      item.priority = params[:priority]
      item.date = Date.parse params[:date]
      item.save!

      redirect_to '/'
    end
  end

  def complete
    item = Item.find params[:id]
    item.destroy
    redirect_to '/'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MxitToDo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/list/add/content.html.erb
<%= content_for :title do %>Add Item<% end %>
<%= content_for :navigation do %><%= mxit_nav_link '/', 'Cancel' %><% end %>

<p>You are adding a new item to the top of your to-do list</p>

app/views/list/add/date.html.erb
<%= content_for :title do %>Add Item<% end %>
<%= content_for :navigation do %><%= mxit_nav_link '/', 'Cancel' %><% end %>

<p>New to-do item: <b><%= @content %></b></p>

app/views/list/add/priority.html.erb
<%= content_for :title do %>Add Item<% end %>
<%= content_for :navigation do %><%= mxit_nav_link '/', 'Cancel' %><% end %>

<p>New to-do item: <b><%= @content %></b></p>

<p>Please enter a priority from 1 (very important) to 5 (not at all important)</p>

app/views/list/index.html.erb
<%= content_for :title do %>To-Do<% end %>

<% if @items.empty? %>
  <p>Hooray!  You've got nothing left to do</p>
<% else %>
  <% @items.each do |item| %>
    <p>
      <b>- <%= item.content %></b>
      <%= mxit_link complete_item_url(:id => item.id), 'complete' %>
      <br>
      &nbsp;&nbsp;&nbsp;<i>Due by <%= item.date %></i><br />
      &nbsp;&nbsp;&nbsp;(Priority: <%= item.priority %>)
    <p>
  <% end %>
<% end %>

<%= mxit_link add_item_url, 'Add an item' %>